routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/homeadmin', 'HomeController@homeAdmin')->name('homeadmin')->middleware('auth');
Auth::routes();

    
    Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
    Route::get('/login/user', 'Auth\LoginController@showUserLoginForm');
    Route::get('/register/admin', 'Auth\RegisterController@showAdminRegisterForm');
    Route::get('/register/user', 'Auth\RegisterController@showUserRegisterForm');

    Route::post('/login/admin', 'Auth\LoginController@adminLogin');
    Route::post('/login/user', 'Auth\LoginController@userLogin');
    Route::post('/register/admin', 'Auth\RegisterController@createAdmin');
    Route::post('/register/user', 'Auth\RegisterController@createUser');

    //Route::view('/home', 'home')->middleware('auth');
    Route::view('/admin', 'admin.home');
    Route::view('/user', 'home');
   



//admin
Route::resource('/kategori', 'CategoryController')->except([
    'create', 'show'
]);
Route::resource('/produk', 'ProductController');
Route::get('/transaksi', 'OrderController@addOrder');

//user
Route::resource('shop', 'ListController', ['only' => ['index', 'show']]);
Route::resource('cart', 'CartController');
Route::delete('emptyCart', 'CartController@emptyCart');
Route::get('/checkout', 'CartController@confirmcheckout')->name('order.checkout');


Route::post('/buy', 'CartController@storeCheckout')->name('buyorder');
Route::get('/konfirmasi', 'OrderController@confirmOrder');


Route::get('ongkir', 'ShippingController@getProvince');
Route::get('getcity', 'ShippingController@getCity');
Route::get('cekongkir', 'ShippingController@checkShipping');
Route::post('/prosesshipping', 'ShippingController@prosesShipping')->name('proses');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $guarded = [];
    public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;
use File;
use Image;


class ProductController extends Controller
{
    //
    public function index(){
        $products = Product::with('category')->orderBy('created_at', 'DESC')->paginate(10);
            return view('admin.products.index', compact('products'));
    }

    public function create(){
        $categories = Category::orderBy('name', 'ASC')->get();
            return view('admin.products.create', compact('categories'));
    }

    public function store(Request $request){
        //validasi data
        $this->validate($request, [
            'code' => 'required|string|max:15|unique:products',
            'name' => 'required|string|max:100',
            'description' => 'nullable|string|max:100',
            'stock' => 'required|integer',
            'weight' => 'required|integer',
            'price' => 'required|integer',
            'category_id' => 'required|exists:categories,id',
            'photo' => 'nullable|image|mimes:jpg,png,jpeg'
        ]);

        try {
            //default photo kosong
            $photo=null;
            //file photo
            if($request->hasFile('photo')){
                //method save file photo
                $photo = $this->saveFile($request->name, $request->file('photo'));
            }

            //simpan data ke table
            $product = Product::create([
                'code' => $request->code,
                'name' => $request->name,
                'description' => $request->description,
                'stock' => $request->stock,
                'weight' => $request->weight,
                'price' => $request->price,
                'category_id' => $request->category_id,
                'photo' => $photo
            ]);

            //direct ke halaman produk.index
            return redirect(route('admin.produk.index'))
                ->with(['success' => '<strong>' . $product->name . '</strong> Ditambahkan' ]);
        }catch (\Exception $e){
            //jika aksi gagal kembali ke halaman sebelumnya
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }

    }

    private function saveFile($name, $photo){
        //set nama file adalah gabungan antara nama produk dan time(). Ekstensi gambar tetap dipertahankan
        $images = str_slug($name) . time() . '.' . $photo->getClientOriginalExtension();
        
        //simpan gambar ke folder
        $path = public_path('uploads/product');

        //cek jika uploads/product bukan folder
        if (!File::isDirectory($path)){
            //buat folder
            File::makeDirectory($path, 0777, true, true);
        }

        //simpan gambar yang diuplaod ke folrder uploads/produk
        Image::make($photo)->save($path . '/' . $images);
        //mengembalikan nama file yang ditampung divariable $images
        return $images;
    }


    public function destroy($id){
        //query select id
        $products = Product::findOrfail($id);

        if(!empty($products->photo)){
            File::delete(public_path('uploads/product/'. $products->photo));
        }

        //hapus data table
        $products->delete();

        return redirect()->back()->with(['success' => '<strong>' . $products->name .'</strong> Dihapus']);
    }

    public function edit($id){
        $product = Product::findOrfail($id);
        $categories = Category::orderBy('name', 'ASC')->get();
        return view('admin.products.edit', compact('product', 'categories'));
    }

    public function update(Request $request, $id){
        //validasi
        $this->validate($request, [
            'code' => 'required|string|max:20|exists:products,code',
            'name' => 'required|string|max:25',
            'description' => 'nullable|string|max:100',
            'stock' => 'required|integer',
            'weight' => 'required|integer',
            'price' => 'required|integer',
            'category_id' => 'required|exists:categories,id',
            'photo' => 'image|mimes:jpg,png,jpeg'
        ]);

        try{
            $product = Product::findOrfail($id);
            $photo = $product->photo;

            //cek file dari form
            if ($request->hasFile('photo')) {
                //cek jika photo tidak kosong maka file yang ada di folder akan dihapus
                !empty($photo) ? File::delete(public_path('uploads/product/'. $photo)):null;
                //upload file dengan method saveFile() yang telah dibuat sebelumnya
                $photo = $this->saveFile($request->name, $request->file('photo'));
            }

            //update dATA DATABASE
            $product->update([
                'name' => $request->name,
                'description' => $request->description,
                'stock' => $request->stock,
                'weight' => $request->weight,
                'price' => $request->price,
                'category_id' => $request->category_id,
                'photo' => $photo
            ]);
            return redirect(route('produk.index'))
                ->with(['success' => '<strong>'. $product->name . '</strong> di Update' ]);
        } catch (\Exception $e){
            return redirect()->back()->with(['error' => $e->getMessage()]);
        }
    }
    



}

resources/views/admin/products/create.blade.php
@extends('layouts.master')

@section('title')
    <title>Input Data Produk</title>\
@endsection    

@section('content')
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Tambah Data</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('produk.index') }}">Produk</a></li>
                            <li class="breadcrumb-item active">Tambah</li>
                        </ol>
                    </div>
                </div>   
            </div>
        </div> 
        
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        @card 
                            @slot('title')
                            @endslot

                            @if (session('success'))
                                @alert (['type' => 'success'])
                                    (!! session('success')!!)
                                @endalert
                            @endif
                            
                            <form action="{{ route('produk.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="">Kode Produk</label>
                                    <input type="text" name="code" required maxlength="10"
                                        class="form-control {{ $errors->has('code') ? 'is-invalid':''}}">
                                    <p class="text-danger">{{ $errors->first('code') }}</p>    
                                </div>

                                <div class="form-group">
                                    <label for="">Nama Produk</label>
                                    <input type="text" name="name" required 
                                        class="form-control {{ $errors->has('name') ? 'is-invalid':''}}">
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                     
                                </div>

                                <div class="form-group">
                                    <label for="">Deskripsi</label>
                                    <textarea name="description" id="description" cols="5" rows="5"
                                        class="form-control {{ $errors->has('description') ? 'is-invalid':'' }}"></textarea>
                                    <p class="text-danger">{{ $errors->first('description') }}</p>    
                                </div>

                                <div class="form-group">
                                    <label for="">Stok</label>
                                    <input type="number" name="stock" required
                                        class="form-control {{ $errors->has('stock') ? 'is-invalid':'' }}">
                                    <p class="text-danger">{{ $errors->first('stock') }}</p>     
                                </div>


                                <div class="form-group">
                                    <label for="">Berat</label>
                                    <input type="number" name="weight" required
                                        class="form-control {{ $errors->has('weight') ? 'is-invalid':'' }}">
                                    <p class="text-danger">{{ $errors->first('weight') }}</p>     
                                </div>
                                
                                <div class="form-group">
                                    <label for="">Harga</label>
                                    <input type="number" name="price" required
                                        class="form-control {{ $errors->has('price') ? 'is-invalid':'' }}">
                                    <p class="text-danger">{{ $errors->first('price') }}</p>                            
                                </div>

                                <div class="form-group">
                                    <label for="">Kategori</label>
                                    <select name="category_id" id="category-id" required
                                        class="form-control {{ $errors->has('price' ? 'is-invalid':'' )}}">
                                        <option value="">Pilih</option>
                                        @foreach ($categories as $row)
                                            <option value="{{ $row->id }}">{{ ucfirst($row->name) }}</option>
                                        @endforeach    
                                    </select>
                                    <p class="text-danger">{{ $errors->first('category_id') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="">Foto</label>
                                    <input type="file" name="photo" class="form-control">
                                    <p class="text-danger">{{ $errors->first('photo') }}</p>
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">
                                        <i class="fa fa-send"></i> Simpan
                                    </button>
                                </div>                                
                            </form>
                            @slot('footer')
                            @endslot
                        @endcard    
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection    

resources/views/admin/products/edit.blade.php
@extends('layouts.master')

@section('title')
    <title> Edit Data Produk</title>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Edit Data</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ route('produk.index') }}">Produk</a></li>
                            <li class="breadcrumb-item active">Edit</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        @card 
                            @slot('title')

                            @endslot

                            @if (session('error'))
                                @alert(['type' => 'danger'])
                                    {{!! session('error') !!}}
                                @endalert
                            @endif
                            
                            <form action="{{ route('produk.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <input type="hidden" name="_method" value="PUT">
                                <div class="form-group">
                                    <label for="">Kode Produk</label>
                                    <input type="text" name="code" required maxlength="10" readonly 
                                        value="{{ $product-> code}}" 
                                        class="form control {{ $errors->has('code') ? 'is-invalid':'' }}">
                                    <p class="text-danger">{{ $errors->first('code') }}</p>    
                                </div>

                                <div class="form-group">
                                    <label for="">Nama</label>
                                    <input type="text" name="name" required
                                        value="{{$product->name}}"
                                        class="form-control {{$errors->has('name') ? 'is-invalid':'' }}">
                                    <p class="text-danger">{{ $errors->first('name')}}</p>    
                                </div>

                                <div class="form-group">
                                    <label for="">Deskripsi</label>
                                    <textarea name="description" id="description" cols="5" rows="5"
                                        class="form-control {{ $errors->has('description') ? 'is-invalid':'' }}">{{ $product->description }}</textarea> 
                                    <p class="text-danger">{{ $errors->first('description') }}</p> 
                                </div>
                                
                                <div class="form-group">
                                    <label for="">Stok</label>
                                    <input type="number" name="stock" required 
                                        value="{{ $product->stock }}"
                                        class="form-control {{ $errors->has('stock') ? 'is-invalid':'' }}">
                                    <p class="text-danger">{{ $errors->first('stock') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="">Berat</label>
                                    <input type="number" name="weight" required
                                        value="{{ $product->weight }}"
                                        class="form-control {{ $errors->has('weight') ? 'is-invalid':'' }}">
                                    <p class="text-danger">{{ $errors->first('weight') }}</p>     
                                </div>
                                
                                <div class="form-group">
                                    <label for="">Harga</label>
                                    <input type="number" name="price" required 
                                        value="{{ $product->price }}"
                                        class="form-control {{ $errors->has('price') ? 'is-invalid':'' }}">
                                    <p class="text-danger">{{ $errors->first('price') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="">Kategori</label>
                                    <select name="category_id" id="category_id" required
                                        class="form-control {{ $errors->has('price') ? 'is-invalid':'' }}">
                                        <option value="">--Pilih--</option>
                                        @foreach ($categories as $row)
                                            <option value="{{ $row->id }}" {{ $row->id == $product->category_id ? 'selected':'' }}>
                                                {{ ucfirst($row->name) }}
                                            </option>
                                        @endforeach    
                                    </select>
                                    <p class="text-danger"> {{ $errors->first('category_id') }}</p>
                                </div>

                                <div class="form-group">
                                    <label for="">Foto</label>
                                    <input type="file" name="photo" class="form-control">
                                    <p class="text-danger">{{ $errors->first('photo') }}</p>
                                    @if (!empty($product->photo))
                                    <hr>
                                    <img src="{{ asset('uploads/product/' . $product->photo) }}"
                                        alt="{{ $product->name }}" width="150px" height="150px">
                                    @endif    
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-info btn-sm">
                                        <i class="fa fa-refresh"></i> Update
                                    </button>
                                </div>
                            </form>
                            @slot('footer')

                            @endslot
                        @endcard
                </div>
            </div>
        </section>
    </div>  
@endsection    

resources/views/admin/products/index.blade.php
@extends('layouts.master')

@section('title')
    <title> Manajemen Produkk </title>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Manajemen Produk</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Produk</li>
                        </ol>                        
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        @card 
                            @slot('title')
                            <a href="{{ route('produk.create')}}" class="btn btn-primary btn-sm">
                                <i class="fa fa-edit"></i>Tambah
                            </a>
                            @endslot

                            @if (session('success'))
                                @alert(['type' => 'success'])
                                    {!! session('success')!!}
                                @endalert
                            @endif
                            
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nama Produk</th>
                                            <th>Stok</th>
                                            <th>Berat</th>
                                            <th>Harga</th>
                                            <th>Kategori</th>
                                            <th>Last Update</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($products as $row)
                                        <tr>
                                            <td> <img src="{{ asset('uploads/product/'. $row->photo) }}"
                                                    alt="{{ $row->name }}" width="50px" height="50px">
                                            </td>
                                            <td>
                                                <sup class="label label-success">({{ $row->code }})</sup>
                                                <strong>{{ ucfirst($row->name) }}</strong>
                                            </td>
                                            <td> {{$row->stock}} </td>
                                            <td> {{$row->weight}} g </td>
                                            <td>Rp. {{ number_format($row->price) }}</td>
                                            <td>{{ $row->category->name}}</td>
                                            <td>{{ $row->updated_at }}</td>
                                            <td>
                                                <form action="{{ route('produk.destroy', $row->id) }}" method="POST">
                                                    @csrf
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <a href="{{ route('produk.edit', $row->id) }}" 
                                                        class="btn btn-warning btn-sm">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i>
                                                    </button>
                                                </form>            
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                                <td colspan="7" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>                            
                                </table>
                                <div class="float-right">
                                    {!! $products->links() !!}
                                </div>
                            @slot('footer')

                            @endslot
                        @endcard    

                    </div>
                </div>
            </div>
        </section>
    </div>
    @endsection